# Generated by Django 5.2 on 2025-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipoVehiculo',
                'verbose_name_plural': 'tipoVehiculo',
                'db_table': 'tipoVehiculo',
            },
        ),
    ]
