# Generated by Django 5.2 on 2025-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('patente', models.CharField(max_length=15)),
                ('pie', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_cuotas', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Contratos',
                'verbose_name_plural': 'Contratos',
                'db_table': 'Contratos',
            },
        ),
    ]
