# Generated by Django 5.2 on 2025-11-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_arriendo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_arrendatario', models.CharField(max_length=12)),
                ('nombre_arrendatario', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor_arriendo', models.IntegerField()),
                ('tipo_arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='tipo_arriendo.tipoarriendo')),
            ],
        ),
    ]
