# Generated by Django 5.2 on 2025-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipopago',
                'verbose_name_plural': 'tipoPagos',
                'db_table': 'tipopago',
            },
        ),
    ]
