# Generated by Django 5.2 on 2025-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('tipo_costo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Costos',
                'verbose_name_plural': 'Costos',
                'db_table': 'costos',
            },
        ),
    ]
