# Generated by Django 5.2 on 2026-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costos',
            name='numero_boleta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
