# Generated by Django 5.2 on 2025-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trasmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transmision', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'transmision',
                'verbose_name_plural': 'transmision',
                'db_table': 'transmision',
            },
        ),
    ]
