# Generated by Django 5.2 on 2025-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=15, null=True, unique=True)),
                ('clave', models.CharField(max_length=120, null=True)),
                ('comision', models.FloatField(null=True)),
                ('nivel', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Vendedores',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
            },
        ),
    ]
