# Generated by Django 5.2 on 2025-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('comision', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Vendedores',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
            },
        ),
    ]
