# Generated by Django 5.2 on 2025-06-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='comision',
            field=models.FloatField(null=True),
        ),
    ]
