# Generated by Django 5.2 on 2026-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='activo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
