# Generated by Django 5.2 on 2025-07-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_alter_vendedores_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='clave',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vendedores',
            name='nivel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vendedores',
            name='usuario',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
