# Generated by Django 5.2 on 2025-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0003_vendedores_clave_vendedores_nivel_vendedores_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='nivel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
