# Generated by Django 5.2 on 2026-01-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='habilitado_venta',
            field=models.BooleanField(default=False),
        ),
    ]
