# Generated by Django 5.2 on 2025-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerarCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(help_text='RUT del cliente asociado a la cuota.', max_length=12)),
                ('patente', models.CharField(help_text='Patente del vehículo asociado al préstamo.', max_length=10)),
                ('numero_cuota', models.IntegerField(help_text='Número de la cuota dentro del total (1, 2, 3...).')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite de pago de la cuota.')),
                ('monto_cuota', models.DecimalField(decimal_places=2, help_text='Monto total a pagar en esta cuota.', max_digits=10)),
                ('abono_capital', models.DecimalField(decimal_places=2, help_text='Porción del pago que amortiza el capital principal.', max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en que se efectuó el pago.', null=True)),
                ('observacion', models.TextField(blank=True, help_text='Cualquier nota adicional sobre el pago.', null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generar Cuotas',
                'verbose_name_plural': 'generar cuotas',
                'unique_together': {('patente', 'numero_cuota')},
            },
        ),
    ]
