# Generated by Django 5.2 on 2026-01-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarCuotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generarcuotas',
            unique_together={('rut_cliente', 'patente', 'numero_cuota')},
        ),
    ]
