# Generated by Django 5.2 on 2025-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=15)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('patente_vehiculo', models.CharField(max_length=15)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('valor_pie', models.IntegerField()),
                ('numero_cuotas', models.IntegerField()),
                ('monto_a_financiar', models.IntegerField()),
                ('valor_cuota', models.IntegerField()),
                ('interes_mensual', models.FloatField()),
                ('valor_venta_total', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default='2023-01-01 00:00:00')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuesto',
                'db_table': 'presupuesto',
            },
        ),
    ]
