# Generated by Django 5.2 on 2025-06-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
