# Generated by Django 5.2 on 2026-01-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('rut_cliente', 'patente_vehiculo')},
        ),
    ]
