# Generated by Django 5.2 on 2026-01-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_alter_presupuesto_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together=set(),
        ),
    ]
