# Generated by Django 5.2 on 2025-06-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_alter_presupuesto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='rut_vendedor',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
