# Generated by Django 5.2 on 2026-03-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_alter_presupuesto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='pausa',
            field=models.IntegerField(default=0),
        ),
    ]
