# Generated by Django 5.2 on 2025-06-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_presupuesto_rut_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='valor_venta_total',
        ),
    ]
