# Generated by Django 5.2 on 2026-03-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_presupuesto_pausa'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='numero_contrato',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
