# Generated by Django 5.2 on 2025-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_remove_presupuesto_valor_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_inicio_pago',
            field=models.DateField(null=True),
        ),
    ]
