# Generated by Django 5.2 on 2025-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_presupuesto_fecha_inicio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='precio_venta',
            field=models.IntegerField(null=True),
        ),
    ]
