# Generated by Django 5.2 on 2025-08-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_presupuesto_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
    ]
