# Generated by Django 5.2 on 2025-09-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0007_alter_presupuesto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
