# Generated by Django 5.2 on 2025-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0008_alter_presupuesto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
