# Generated by Django 5.2 on 2025-10-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0010_alter_presupuesto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
