# Generated by Django 5.2 on 2025-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de arriendo', max_length=100, unique=True)),
                ('comision', models.DecimalField(decimal_places=1, default=0.0, help_text='Comisión en porcentaje (ej. 10.5)', max_digits=3)),
            ],
            options={
                'verbose_name': 'Tipo de Arriendo',
                'verbose_name_plural': 'Tipos de Arriendo',
                'ordering': ['nombre'],
            },
        ),
    ]
