# Generated by Django 5.2 on 2025-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePagoCuotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('patente', models.CharField(max_length=10)),
                ('numero_cuota', models.IntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_abono', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detalle de Pago de Cuota',
                'verbose_name_plural': 'Detalles de Pago de Cuotas',
                'db_table': 'detalle_pago',
            },
        ),
    ]
