# Generated by Django 5.2 on 2025-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePagoCuotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, null=True)),
                ('patente', models.CharField(max_length=10, null=True)),
                ('numero_cuota', models.IntegerField(null=True)),
                ('monto_cuota', models.IntegerField(null=True)),
                ('interes', models.FloatField(null=True)),
                ('capital', models.IntegerField(null=True)),
                ('fecha_abono', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'detalle_pago',
                'verbose_name_plural': 'detalle_pago',
                'db_table': 'detalle_pago',
            },
        ),
    ]
