# Generated by Django 5.2 on 2026-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallePagoCuotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepagocuotas',
            name='numero_contrato',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
