# Generated by Django 5.2 on 2025-06-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallePagoCuotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepagocuotas',
            name='monto_cuota',
            field=models.IntegerField(),
        ),
    ]
