# Generated by Django 5.2 on 2025-06-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallePagoCuotas', '0002_alter_detallepagocuotas_monto_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepagocuotas',
            name='capital',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detallepagocuotas',
            name='interes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detallepagocuotas',
            name='monto_cuota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallepagocuotas',
            name='numero_cuota',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallepagocuotas',
            name='patente',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallepagocuotas',
            name='rut',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
