# Generated by Django 5.2 on 2025-07-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detallePagoCuotas', '0003_detallepagocuotas_capital_detallepagocuotas_interes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepagocuotas',
            options={'verbose_name': 'detalle_pago', 'verbose_name_plural': 'detalle_pago'},
        ),
    ]
