# Generated by Django 5.2 on 2025-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallePagoCuotas', '0004_alter_detallepagocuotas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepagocuotas',
            name='fecha_abono',
            field=models.DateField(auto_now_add=True),
        ),
    ]
