# Generated by Django 5.2 on 2025-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=15, null=True)),
                ('patente', models.CharField(max_length=15, null=True)),
                ('numero_cuota', models.IntegerField(null=True)),
                ('monto_cuota', models.IntegerField(null=True)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('fecha_pago', models.DateField(null=True)),
                ('observacion', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'pago_cuotas',
                'verbose_name_plural': 'Pago_cuotas',
                'db_table': 'pago_cuotas',
                'ordering': ['numero_cuota'],
            },
        ),
    ]
