# Generated by Django 5.2 on 2025-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagocuotas',
            options={'ordering': ['numero_cuota', 'rut_cliente', 'patente'], 'verbose_name': 'pago_cuotas', 'verbose_name_plural': 'Pago_cuotas'},
        ),
        migrations.AddField(
            model_name='pagocuotas',
            name='capital_cuota',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagocuotas',
            name='interes_mensual',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pagocuotas',
            name='monto_prestamo',
            field=models.IntegerField(null=True),
        ),
    ]
