# Generated by Django 5.2 on 2025-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0002_alter_pagocuotas_options_pagocuotas_capital_cuota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuotas',
            name='interes_mensual',
            field=models.FloatField(null=True),
        ),
    ]
