# Generated by Django 5.2 on 2026-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0002_pagocuotas_interes_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuotas',
            name='numero_contrato',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagocuotas',
            name='observacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
