# Generated by Django 5.2 on 2025-06-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0003_alter_pagocuotas_interes_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuotas',
            name='saldo_pendiente_final',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pagocuotas',
            name='interes_mensual',
            field=models.IntegerField(null=True),
        ),
    ]
