# Generated by Django 5.2 on 2025-06-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0004_pagocuotas_saldo_pendiente_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuotas',
            name='interes_mensual',
            field=models.FloatField(null=True),
        ),
    ]
