# Generated by Django 5.2 on 2025-07-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0005_alter_pagocuotas_interes_mensual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocuotas',
            name='saldo_pendiente_final',
        ),
    ]
