# Generated by Django 5.2 on 2025-07-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0006_remove_pagocuotas_saldo_pendiente_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagocuotas',
            old_name='capital_cuota',
            new_name='abono_capital',
        ),
    ]
