# Generated by Django 5.2 on 2025-08-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0007_rename_capital_cuota_pagocuotas_abono_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuotas',
            name='observacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
