# Generated by Django 5.2 on 2025-09-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0008_alter_pagocuotas_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocuotas',
            name='interes_mensual',
        ),
    ]
