# Generated by Django 5.2 on 2025-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoCuotas', '0009_remove_pagocuotas_interes_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuotas',
            name='interes_mensual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pagocuotas',
            name='observacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
