# Generated by Django 5.2 on 2025-11-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('tipoVehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustible', models.IntegerField()),
                ('tipo_trasmision', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('agno', models.CharField(max_length=4)),
                ('numero_motor', models.CharField(max_length=30)),
                ('numero_chasis', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=15, unique=True)),
                ('kilometraje', models.IntegerField()),
                ('estado', models.IntegerField(null=True)),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField(default=0, null=True)),
                ('propiedad_automotriz', models.IntegerField(null=True)),
                ('tipo_marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marca.marca')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipoVehiculo.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
            },
        ),
    ]
