# Generated by Django 5.2 on 2025-06-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='interes_cuota',
        ),
    ]
