# Generated by Django 5.2 on 2025-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='fecha_revision_tecnica',
            field=models.DateField(blank=True, null=True),
        ),
    ]
