# Generated by Django 5.2 on 2025-12-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculos_fecha_revision_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='revision_tecnica_al_dia',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
