# Generated by Django 5.2 on 2025-06-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_vehiculos_interes_cuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='margen',
        ),
    ]
