# Generated by Django 5.2 on 2025-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_remove_vehiculos_margen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='estado',
            field=models.IntegerField(null=True),
        ),
    ]
