# Generated by Django 5.2 on 2025-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculos_revision_tecnica_al_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='permiso_circulacion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='seguro_vigente',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
