# Generated by Django 5.2 on 2025-12-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculos_permiso_circulacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='fecha_revision_tecnica',
        ),
    ]
