# Generated by Django 5.2 on 2025-06-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_vehiculos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='patente',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
