# Generated by Django 5.2 on 2025-06-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_alter_vehiculos_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='gastos_asociados',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='precio_venta',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
