# Generated by Django 5.2 on 2026-01-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_remove_vehiculos_fecha_revision_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='habilitado_venta',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
