# Generated by Django 5.2 on 2026-01-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_vehiculos_habilitado_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='habilitado_compra',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
