# Generated by Django 5.2 on 2025-06-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_vehiculos_gastos_asociados_vehiculos_precio_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='gastos_asociados',
        ),
    ]
