# Generated by Django 5.2 on 2026-01-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_vehiculos_habilitado_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='habilitado_compra',
        ),
    ]
