# Generated by Django 5.2 on 2025-10-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_remove_vehiculos_gastos_asociados'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='propiedad_automotriz',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
