# Generated by Django 5.2 on 2025-10-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_vehiculos_propiedad_automotriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='propiedad_automotriz',
            field=models.IntegerField(null=True),
        ),
    ]
