# Generated by Django 5.2 on 2026-01-21 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario', models.CharField(db_index=True, max_length=100)),
                ('pagina', models.CharField(help_text='Página desde donde se realizó el cambio', max_length=200)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar')], db_index=True, max_length=20)),
                ('modulo_tabla', models.CharField(db_index=True, help_text='Módulo o tabla afectada', max_length=100)),
                ('descripcion', models.TextField()),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
