# Generated by Django 5.2 on 2026-02-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='pagina',
        ),
    ]
